services:
  # Laravel (PHP-FPM)
  app:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    container_name: lms-laravel-app
    working_dir: /var/www/html
    volumes:
      - ../backend:/var/www/html
    depends_on:
      - mysql-lms
      - redis
    environment:
      - DB_HOST=mysql-lms
      - DB_PORT=3306
    networks:
      - network-lms

  # Nginx
  web:
    image: nginx:alpine
    container_name: lms-nginx
    ports:
      - "9080:80"
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - network-lms

  # MySQL
  mysql-lms:
    image: mysql:8.0
    container_name: lms-mysql
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_lms
    volumes:
      # - lms-mysql-data:/var/lib/mysql
      - ./db:/var/lib/mysql   # mount ra thư mục db trong dự án
    networks:
      - network-lms

  # Redis
  redis:
    image: redis:alpine
    container_name: lms-redis
    ports:
      - "9379:6379"
    networks:
      - network-lms

  # Mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: lms-mailhog
    ports:
      - "9025:8025"
      - "9125:1025"
    networks:
      - network-lms

  # ReactJS + Vite
  frontend:
    image: node:23.6.0
    container_name: lms-react-app
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - network-lms

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lms-phpmyadmin
    ports:
      - "9180:80"
    environment:
      PMA_HOST: mysql-lms
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql-lms
    networks:
      - network-lms

volumes:
  lms-mysql-data:

networks:
  network-lms:
    driver: bridge